name: Setup repository
on:
  push: {}

jobs:
  validate:
    name: Validate repository
    runs-on: ubuntu-latest
    steps:
      - name: Check if repo is a template repository
        id: checkRepo
        uses: actions/github-script@v4
        with:
          script: |
            const repo = await github.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              headers: {
                accept: 'application/vnd.github.baptiste-preview+json'
              }
            });

            return {
              template: repo.data.is_template,
              name: context.repo.repo,
            };

      - name: Log output
        run: echo "$RESULT"
        env:
          RESULT: ${{ steps.checkRepo.outputs.result }}

    outputs:
      isTemplate: ${{ fromJSON(steps.checkRepo.outputs.result).template }}
      name: ${{ fromJSON(steps.checkRepo.outputs.result).name }}

  setup:
    name: Reinitialize repository
    runs-on: ubuntu-latest
    needs: [validate]
    if: ${{ !fromJSON(needs.validate.outputs.isTemplate) }}
    steps:
      - uses: actions/checkout@v2

      - name: Create cookiecutter.json
        uses: actions/github-script@v4
        with:
          script: |
            const config = { name: context.repo.repo };
            require('fs').writeFileSync('cookiecutter.json', JSON.stringify(config), { encoding: 'utf-8' });

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install cookiecutter

      - name: Scaffolding repository
        # cookiecutter is command-line utility to create projects from templates
        # https://github.com/cookiecutter/cookiecutter
        #
        # --no-input      Do not prompt for parameters and only use
        #                 cookiecutter.json file content
        #
        # --output-dir    Where to output the generated project dir into
        run: cookiecutter . --no-input --output-dir ./cookiecutter-temp

      - name: Prepare root directory
        shell: bash
        # Remove {{cookiecutter.name}} and setup-repository workflow
        run: rm -rf '{{cookiecutter.name}}' && rm .github/workflows/setup-repository.yml

      - name: Move files to root
        shell: bash
        # The cookiecutter-temp/ folder contains a single folder which is the
        # generated project by cookiecutter. We want to move all the project
        # files into the root directory so we can reinitialize git in the next step
        run: |
          rsync -r ./cookiecutter-temp/*/ . && \
          rm -rf ./cookiecutter-temp/

      - name: Remove git files
        run: rm -rf .git

      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: '.'

      # - name: Reinitialize git repository
      #   shell: bash
      #   # Reinitialize git after scaffolding this repository.
      #   # We use `git checkout --orphan` to create a branch in a git init-like state.
      #   # By force pushing this as `main` we end up with a new clean git history.
      #   run: |
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
      #     git config --global user.name "github-actions[bot]" && \
      #     git checkout --orphan temp-branch && \
      #     git add . && \
      #     git commit -m 'Initial commit' && \
      #     git push origin temp-branch:main -f
